### ISSUE TITLE
partialTrace

### ISSUE THREAD

**Issue by rezah** [yingjerkao/uni10#12]
partialTrace:
Two bonds are of the same type but it could not recognize it!!!:
bonds of given two labels does not match for trace

Please see the attached file,
[Uni10.cpp.tar.gz](https://github.com/yingjerkao/uni10/files/477106/Uni10.cpp.tar.gz)

commit c764d78..8e3f5df probably solves the issue.

**Comment by yingjerkao** [comment]
@Yun-Hsuan  Please review the commit.

**Comment by yingjerkao** [comment]
8e3f5df fixes this issue. Issue closed
