### ISSUE TITLE
Higher Order Singular Value Decomposition

### ISSUE THREAD

**Issue by Wangwei-Lan** [yingjerkao/uni10#15]
Dear Uni10 Developer,

I am pretty new in using Uni10. Recently, I was trying to write a MPS, which requires svd a lot. However, UniTensor seems don't support svd but rather higher order svd. Could you please provide some examples on this function?  Because HOSVD is a little bit confusing to me. 

I was trying to write a right canonical MPS from a random MPS. Was that possible within the code you have now? Thanks very much.

Yours Sincerely
Baicai

**Comment by yingjerkao** [comment]
@XiaoXiaoBaiCai 

The SVD is implemented in `Block` and `Matrix`.  
You need to use `UniTensor.getBlock()` to get the pointer and perform SVD.
