### ISSUE TITLE
Any updated version? 

### ISSUE THREAD

**Issue by rezah** [yingjerkao/uni10#30]
It has been two years, but uni10 has not yet received any new updated version. I am wondering this project is still active or not. please inform me and other users.

**Comment by yingjerkao** [comment]
`Uni10` C++ v2.0 will be released next week. 

`PyUni10` v2.0 will be released separately Anaconda cloud and PyPi soon, after we resolve some technical issues.  

Sneak preview of  new features

  * Major API changes, `Matrix` and `UniTensor` are changed to class templates.
    Linear algebra operations are changed to global functions.

  * Official CUDA GPU support for double precision.  

  * New architecture design to allow support for different architectures and
    customized containers and linear algebra libraries.

  * Optimization of the network contraction engine to reduce the memory
    requirements and speedup computation.

  * Better integration with `numpy` in `PyUni10` 

We are preparing to open our development repo so users can see the updates and contribute more easily. Sorry for the long delay.
