### ISSUE TITLE
BUILD_WITH_INTEL_COMPILERS doesn't seem to work

### ISSUE THREAD

**Issue by Meligordman** [yingjerkao/uni10#5]
I have Intel Parallel Studio XE Cluster Edition for Linux 2015 and 2016 installed.
Activating the option BUILD_WITH_INTEL_COMPILERS does not seem to be working, since it returns 

> --  CXX Compiler: /usr/bin/c++

a GCC compiler. Is it possible to manually set the path to `icpc`?

**Comment by cylo** [comment]
@Meligordman 
Have you tried
`source /opt/intel/bin/compilervars.sh intel64`  or
`source /opt/intel/bin/compilervars.sh ia32`  (for 32bit OS)
to specify the location of intel compiler?

**Comment by yingjerkao** [comment]
@Meligordman 
Is your problem solved by @cylo's suggestion?

**Comment by Meligordman** [comment]
Sorry for the delay. I had to travel and forgot to give the feedback.
Yes, apparently it solved the issue. Thank you.
