### ISSUE TITLE
h5save has not been defined

### ISSUE THREAD

**Issue by rezah** [yingjerkao/uni10#7]
## T1.h5save("T1");

error:
‘class uni10::UniTensor’ has no member named ‘h5save’
 T1.h5save("T1");

**Comment by rezah** [comment]
I again write about the issue. May I miss something?

suppose T1 is a uniTensor, by calling the following function, there would be an error,

T1.h5save("T1");

error: error: ‘class uni10::UniTensor’ has no member named ‘h5save’

I've attache the sample code....

[Uni10.cpp.zip](https://github.com/yingjerkao/uni10/files/436274/Uni10.cpp.zip)

I'm looking forward to hearing from you.

**Comment by yingjerkao** [comment]
Bug reproduced. Exploring.

**Comment by yingjerkao** [comment]
Due to the  structure of the `UniTensor.h`, you need to add `-DHDF5` flag when you compile your code.
